from application.models import Teacher
from application.models import Subject
from application import db

yano = Teacher('Yano', 'Edgar Toshiro Yano', 'yano@ita.br', '90', '5891')
alonso = Teacher('Alonso', 'Carlos Alberto Alonso Sanches', 'alonso.ita@gmail.com', '112', '5985')
mirisola = Teacher('Mirisola', 'Luiz Gustavo Bizarro Mirisola', 'luiz.mirisola@gmail.com', '91', '6940')
tassinafo = Teacher('Tassinafo', 'Paulo Marcelo Tasinaffo', 'tasinaffo@ita.br', '95', '6921')
duarte = Teacher('Duarte', 'Duarte Lopes de Oliveira', 'duarte@ita.br', '92', '6813')
osamu = Teacher('Osamu', 'Osamu Saotome', 'osaotome@gmail.com', '93', '5818')
jackson =  Teacher('Jackson', 'Jackson Paul Matsuura', 'jackson@ita.br', '94', '6937')
douglas =  Teacher('Douglas', 'Douglas Soares dos Santos', 'dsoares@ita.br', '187', '6928')
gabriela = Teacher('Gabriela', 'Gabriela Werner Gabriel', 'ggabriel@ita.br', '182', '6955')
manga = Teacher('Maximo', 'Marcos Ricardo Omena de Albuquerque Máximo', 'maximo.marcos@gmail.com', '188', '6958')
brutus = Teacher('Brutus', 'Brutus Abel Fratuce Pimentel', 'brutusabel@hotmail.com', '133', '5543')
cunha = Teacher('Cunha', 'Adilson Marques da Cunha', 'cunha@ita.br', '100', '5598')
inaldo = Teacher('Inaldo', 'Inaldo Capistrano Costa', 'inaldo@ita.br', '111', '5444')
db.session.add(yano)
db.session.add(alonso)
db.session.add(mirisola)
db.session.add(tassinafo)
db.session.add(duarte)
db.session.add(osamu)
db.session.add(jackson)
db.session.add(douglas)
db.session.add(gabriela)
db.session.add(manga)
db.session.add(brutus)
db.session.add(cunha)
db.session.add(inaldo)

<<<<<<< HEAD
ces22 = Subject('CES-22', 'Programação Orientada a Objetos', 'COMP21', 12)
ces12 = Subject('CES-12', 'Algoritmos e Estrutura de Dados II', 'COMP21', 10)
ctc21 = Subject('CTC-21', 'Lógica Matemática e Estruturas Discretas', 'COMP21', 8)
eea21 = Subject('EEA-21', 'Circuitos Digitais', 'COMP21', 15)
ees10 = Subject('EES-10', 'Sistemas de Controle I', 'COMP21', 12)
ele52 = Subject('ELE-52', 'Circuitos Eletrônicos I', 'COMP21', 10)
cmc10 = Subject('CMC-10', 'Projeto e Fabricação de Robôs Móveis', 'Eletiva', 10)
hum32 = Subject('HUM-32', 'Redação Acadêmica', 'Eletiva', 8)
=======
ces22 = Subject('CES-22', 'Programação Orientada a Objetos', 'COMP21', 0, 0, 0, 0, 0)
ces12 = Subject('CES-12', 'Algoritmos e Estrutura de Dados II', 'COMP21', 0, 0, 0, 0, 0)
ctc21 = Subject('CTC-21', 'Lógica Matemática e Estruturas Discretas', 'COMP21', 0, 0, 0, 0, 0)
eea21 = Subject('EEA-21', 'Circuitos Digitais', 'COMP21', 0, 0, 0, 0, 0)
ees10 = Subject('EES-10', 'Sistemas de Controle I', 'COMP21', 0, 0, 0, 0, 0)
ele52 = Subject('ELE-52', 'Circuitos Eletrônicos I', 'COMP21', 0, 0, 0, 0, 0)
cmc10 = Subject('CMC-10', 'Projeto e Fabricação de Robôs Móveis', 'Eletiva', 0, 0, 0, 0, 0)
hum32 = Subject('HUM-32', 'Redação Acadêmica', 'Eletiva', 0, 0, 0, 0, 0)
ces65 = Subject('CES-65', 'Projeto de Sistemas Embarcados', 'Eletiva', 0, 0, 0, 0, 0)
csi02 = Subject('CSI-02', 'Arquitetura Orientada a Serviços', 'Eletiva', 0, 0, 0, 0, 0)
>>>>>>> 5a6bb9de7af55279a8d98cc28f848bd8906cadc4
db.session.add(ces12)
db.session.add(ces22)
db.session.add(ctc21)
db.session.add(eea21)
db.session.add(ees10)
db.session.add(ele52)
db.session.add(cmc10)
db.session.add(hum32)
db.session.add(ces65)
db.session.add(csi02)

ces12.teachers.append(alonso)
ces12.teachers.append(mirisola)
ces22.teachers.append(yano)
ctc21.teachers.append(mirisola)
ctc21.teachers.append(tassinafo)
eea21.teachers.append(duarte)
eea21.teachers.append(osamu)
ees10.teachers.append(jackson)
ees10.teachers.append(gabriela)
ele52.teachers.append(douglas)
cmc10.teachers.append(manga)
hum32.teachers.append(brutus)
ces65.teachers.append(cunha)
csi02.teachers.append(inaldo)

db.session.commit()
