from application.models import Teacher
from application.models import Subject
from application.models import CalendarMonths
from application import db
import datetime

yano = Teacher('Yano', 'Edgar Toshiro Yano', 'yano@ita.br', '90', '5891')
alonso = Teacher('Alonso', 'Carlos Alberto Alonso Sanches', 'alonso.ita@gmail.com', '112', '5985')
mirisola = Teacher('Mirisola', 'Luiz Gustavo Bizarro Mirisola', 'luiz.mirisola@gmail.com', '91', '6940')
tassinafo = Teacher('Tassinafo', 'Paulo Marcelo Tasinaffo', 'tasinaffo@ita.br', '95', '6921')
duarte = Teacher('Duarte', 'Duarte Lopes de Oliveira', 'duarte@ita.br', '92', '6813')
osamu = Teacher('Osamu', 'Osamu Saotome', 'osaotome@gmail.com', '93', '5818')
jackson =  Teacher('Jackson', 'Jackson Paul Matsuura', 'jackson@ita.br', '94', '6937')
douglas =  Teacher('Douglas', 'Douglas Soares dos Santos', 'dsoares@ita.br', '187', '6928')
gabriela = Teacher('Gabriela', 'Gabriela Werner Gabriel', 'ggabriel@ita.br', '182', '6955')
manga = Teacher('Maximo', 'Marcos Ricardo Omena de Albuquerque Máximo', 'maximo.marcos@gmail.com', '188', '6958')
brutus = Teacher('Brutus', 'Brutus Abel Fratuce Pimentel', 'brutusabel@hotmail.com', '133', '5543')
cunha = Teacher('Cunha', 'Adilson Marques da Cunha', 'cunha@ita.br', '100', '5598')
inaldo = Teacher('Inaldo', 'Inaldo Capistrano Costa', 'inaldo@ita.br', '111', '5444')
db.session.add(yano)
db.session.add(alonso)
db.session.add(mirisola)
db.session.add(tassinafo)
db.session.add(duarte)
db.session.add(osamu)
db.session.add(jackson)
db.session.add(douglas)
db.session.add(gabriela)
db.session.add(manga)
db.session.add(brutus)
db.session.add(cunha)
db.session.add(inaldo)

ces22 = Subject('CES-22', 'Programação Orientada a Objetos', 'COMP21', 0, 0, 0, 0, 0, 12)
ces12 = Subject('CES-12', 'Algoritmos e Estrutura de Dados II', 'COMP21', 0, 0, 0, 0, 0, 10)
ctc21 = Subject('CTC-21', 'Lógica Matemática e Estruturas Discretas', 'COMP21', 0, 0, 0, 0, 0, 8)
eea21 = Subject('EEA-21', 'Circuitos Digitais', 'COMP21', 0, 0, 0, 0, 0, 15)
ees10 = Subject('EES-10', 'Sistemas de Controle I', 'COMP21', 0, 0, 0, 0, 0, 12)
ele52 = Subject('ELE-52', 'Circuitos Eletrônicos I', 'COMP21', 0, 0, 0, 0, 0, 10)
cmc10 = Subject('CMC-10', 'Projeto e Fabricação de Robôs Móveis', 'Eletiva', 0, 0, 0, 0, 0, 10)
hum32 = Subject('HUM-32', 'Redação Acadêmica', 'Eletiva', 0, 0, 0, 0, 0, 8)
ces65 = Subject('CES-65', 'Projeto de Sistemas Embarcados', 'Eletiva', 0, 0, 0, 0, 0, 10)
csi02 = Subject('CSI-02', 'Arquitetura Orientada a Serviços', 'Eletiva', 0, 0, 0, 0, 0, 10)

db.session.add(ces12)
db.session.add(ces22)
db.session.add(ctc21)
db.session.add(eea21)
db.session.add(ees10)
db.session.add(ele52)
db.session.add(cmc10)
db.session.add(hum32)
db.session.add(ces65)
db.session.add(csi02)

ces12.teachers.append(alonso)
ces12.teachers.append(mirisola)
ces22.teachers.append(yano)
ctc21.teachers.append(mirisola)
ctc21.teachers.append(tassinafo)
eea21.teachers.append(duarte)
eea21.teachers.append(osamu)
ees10.teachers.append(jackson)
ees10.teachers.append(gabriela)
ele52.teachers.append(douglas)
cmc10.teachers.append(manga)
hum32.teachers.append(brutus)
ces65.teachers.append(cunha)
csi02.teachers.append(inaldo)

dateToStartJan = datetime.datetime(2019, 12, 30, 0, 0)
dateToStartFeb = datetime.datetime(2019, 1, 27, 0, 0)
dateToStartMar = datetime.datetime(2019, 2, 24, 0, 0)
dateToStartApr = datetime.datetime(2019, 3, 31, 0, 0)
dateToStartMay = datetime.datetime(2019, 4, 28, 0, 0)
dateToStartJun = datetime.datetime(2019, 5, 26, 0, 0)
dateToStartJul = datetime.datetime(2019, 6, 30, 0, 0)
dateToStartAug = datetime.datetime(2019, 7, 28, 0, 0)
dateToStartSep = datetime.datetime(2019, 8, 25, 0, 0)
dateToStartOct = datetime.datetime(2019, 9, 29, 0, 0)
dateToStartNov = datetime.datetime(2019, 10, 27, 0, 0)
dateToStartDec = datetime.datetime(2019, 11, 24, 0, 0)

jan = CalendarMonths(1, 2019, dateToStartJan)
fev = CalendarMonths(2, 2019, dateToStartFeb)
mar = CalendarMonths(3, 2019, dateToStartMar)
apr = CalendarMonths(4, 2019, dateToStartApr)
may = CalendarMonths(5, 2019, dateToStartMay)
jun = CalendarMonths(6, 2019, dateToStartJun)
jul = CalendarMonths(7, 2019, dateToStartJul)
aug = CalendarMonths(8, 2019, dateToStartAug)
sep = CalendarMonths(9, 2019, dateToStartSep)
oct = CalendarMonths(10, 2019, dateToStartOct)
nov = CalendarMonths(11, 2019, dateToStartNov)
dec = CalendarMonths(12, 2019, dateToStartDec)

db.session.add(jan)
db.session.add(fev)
db.session.add(mar)
db.session.add(apr)
db.session.add(may)
db.session.add(jun)
db.session.add(jul)
db.session.add(aug)
db.session.add(sep)
db.session.add(oct)
db.session.add(nov)
db.session.add(dec)

db.session.commit()
