"""empty message

Revision ID: 0c6f2ed45549
Revises: dc4e552bb64f
Create Date: 2019-06-25 17:39:00.838617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6f2ed45549'
down_revision = 'dc4e552bb64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_elective_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.Column('raterId', sa.Integer(), nullable=True),
    sa.Column('raterName', sa.String(length=120), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('courseware', sa.Integer(), nullable=False),
    sa.Column('teacherRate', sa.Integer(), nullable=False),
    sa.Column('finalRate', sa.Integer(), nullable=False),
    sa.Column('evaluationMethod', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['raterId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['raterName'], ['user.name'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_elective_subject')
    # ### end Alembic commands ###
