"""empty message

Revision ID: 1c52b45f7012
Revises: 5b1600727ca4
Create Date: 2019-06-26 15:16:12.455823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c52b45f7012'
down_revision = '5b1600727ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('forClass_n_quest', sa.Boolean(), nullable=False))
    op.add_column('activity', sa.Column('forClass_quest', sa.Boolean(), nullable=False))
    op.add_column('activity', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('activity', sa.Column('votes_up', sa.Integer(), nullable=False))
    op.drop_column('activity', 'forClass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('forClass', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('activity', 'votes_up')
    op.drop_column('activity', 'status')
    op.drop_column('activity', 'forClass_quest')
    op.drop_column('activity', 'forClass_n_quest')
    # ### end Alembic commands ###
