"""empty message

Revision ID: 3042a5e6462a
Revises: edcd82839164
Create Date: 2019-06-23 21:51:22.674778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3042a5e6462a'
down_revision = 'edcd82839164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('progress', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'progress')
    # ### end Alembic commands ###
