"""empty message

Revision ID: 5b1600727ca4
Revises: 
Create Date: 2019-06-25 22:56:59.695507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1600727ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_elective_subject', sa.Column('finalRate', sa.Integer(), nullable=False))
    op.add_column('subject', sa.Column('coursewareRate', sa.Float(), nullable=False))
    op.add_column('subject', sa.Column('evaluationMethodRate', sa.Float(), nullable=False))
    op.add_column('subject', sa.Column('finalRate', sa.Float(), nullable=False))
    op.add_column('subject', sa.Column('numberOfRatings', sa.Integer(), nullable=False))
    op.add_column('subject', sa.Column('teachersRate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'teachersRate')
    op.drop_column('subject', 'numberOfRatings')
    op.drop_column('subject', 'finalRate')
    op.drop_column('subject', 'evaluationMethodRate')
    op.drop_column('subject', 'coursewareRate')
    op.drop_column('rating_elective_subject', 'finalRate')
    # ### end Alembic commands ###
