"""empty message

Revision ID: 60e0f70ee342
Revises: 
Create Date: 2019-06-26 15:43:22.242472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e0f70ee342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateToStart', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('classITA', sa.String(length=20), nullable=False),
    sa.Column('lim_abs', sa.Float(), nullable=False),
    sa.Column('numberOfRatings', sa.Integer(), nullable=False),
    sa.Column('finalRate', sa.Float(), nullable=False),
    sa.Column('coursewareRate', sa.Float(), nullable=False),
    sa.Column('teachersRate', sa.Float(), nullable=False),
    sa.Column('evaluationMethodRate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routeIdentifier', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('room', sa.String(length=120), nullable=False),
    sa.Column('ramal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routeIdentifier')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('classITA', sa.String(length=20), nullable=False),
    sa.Column('isRepr', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('abs', sa.Float(), nullable=False),
    sa.Column('just', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_due', sa.Date(), nullable=True),
    sa.Column('forClass_quest', sa.Boolean(), nullable=False),
    sa.Column('forClass_n_quest', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('votes_up', sa.Integer(), nullable=False),
    sa.Column('resp_quest', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_elective_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.Column('raterId', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('courseware', sa.Integer(), nullable=False),
    sa.Column('teacherRate', sa.Integer(), nullable=False),
    sa.Column('finalRate', sa.Integer(), nullable=False),
    sa.Column('evaluationMethod', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['raterId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject-student association',
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['subject.id'], )
    )
    op.create_table('subject-teacher association',
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.Column('teacherId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subjectId'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacherId'], ['teacher.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject-teacher association')
    op.drop_table('subject-student association')
    op.drop_table('rating_elective_subject')
    op.drop_table('activity')
    op.drop_table('absence')
    op.drop_table('user')
    op.drop_table('teacher')
    op.drop_table('subject')
    op.drop_table('calendar_months')
    # ### end Alembic commands ###
