"""empty message

Revision ID: 847b5ba827e1
Revises: 1c52b45f7012
Create Date: 2019-06-26 15:41:23.996704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847b5ba827e1'
down_revision = '1c52b45f7012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('resp_quest', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'resp_quest')
    # ### end Alembic commands ###
