"""empty message

Revision ID: dc4e552bb64f
Revises: b664215d154b
Create Date: 2019-06-25 17:36:42.056513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4e552bb64f'
down_revision = 'b664215d154b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_elective_subject', sa.Column('raterName', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'rating_elective_subject', 'user', ['raterName'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating_elective_subject', type_='foreignkey')
    op.drop_column('rating_elective_subject', 'raterName')
    # ### end Alembic commands ###
