"""empty message

Revision ID: edcd82839164
Revises: 
Create Date: 2019-06-23 20:15:25.124828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcd82839164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'date_due',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'date_due',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
