from application.models import Teacher
from application.models import Subject
from application import db

yano = Teacher(1, 'Yano', 'Edgar Toshiro Yano', 'yano@ita.br', '90', '5891')
alonso = Teacher(2, 'Alonso', 'Carlos Alberto Alonso Sanches', 'alonso.ita@gmail.com', '112', '5985')
mirisola = Teacher(3, 'Mirisola', 'Luiz Gustavo Bizarro Mirisola', 'luiz.mirisola@gmail.com', '91', '6940')
tassinafo = Teacher(4, 'Tassinafo', 'Paulo Marcelo Tasinaffo', 'tasinaffo@ita.br', '95', '6921')
duarte = Teacher(5, 'Duarte', 'Duarte Lopes de Oliveira', 'duarte@ita.br', '92', '6813')
osamu = Teacher(6, 'Osamu', 'Osamu Saotome', 'osaotome@gmail.com', '93', '5818')
jackson =  Teacher(7, 'Jackson', 'Jackson Paul Matsuura', 'jackson@ita.br', '94', '6937')
douglas =  Teacher(8, 'Douglas', 'Douglas Soares dos Santos', 'dsoares@ita.br', '187', '6928')
gabriela = Teacher(9, 'Gabriela', 'Gabriela Werner Gabriel', 'ggabriel@ita.br', '182', '6955')
db.session.add(yano)
db.session.add(alonso)
db.session.add(mirisola)
db.session.add(tassinafo)
db.session.add(duarte)
db.session.add(osamu)
db.session.add(jackson)
db.session.add(douglas)
db.session.add(gabriela)

ces22 = Subject(1, 'CES-22', 'Programação Orientada a Objetos', 'COMP21')
ces12 = Subject(2, 'CES-12', 'Algoritmos e Estrutura de Dados II', 'COMP21')
ctc21 = Subject(5, 'CTC-21', 'Lógica Matemática e Estruturas Discretas', 'COMP21')
eea21 = Subject(7, 'EEA-21', 'Circuitos Digitais', 'COMP21')
ees10 = Subject(8, 'EES-10', 'Sistemas de Controle I', 'COMP21')
ele52 = Subject(6, 'ELE-52', 'Circuitos Eletrônicos I', 'COMP21')
db.session.add(ces12)
db.session.add(ces22)
db.session.add(ctc21)
db.session.add(eea21)
db.session.add(ees10)
db.session.add(ele52)

ces12.teachers.append(alonso)
ces12.teachers.append(mirisola)
ces22.teachers.append(yano)
ctc21.teachers.append(mirisola)
ctc21.teachers.append(tassinafo)
eea21.teachers.append(duarte)
eea21.teachers.append(osamu)
ees10.teachers.append(jackson)
ees10.teachers.append(gabriela)
ele52.teachers.append(douglas)

db.session.commit()